name: spotify_api_repo
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.1
  http: ^1.1.0
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  logging: ^1.2.0
  cookie_jar: 4.0.8

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
